#!/bin/bash
#
# Run from top-level using:
#
# `bash scripts/update.sh`
#
set -e

# TODO: check os before install stumpw

# Switch to this directory
cd "$(dirname "$0")"/..

# update Xresources
echo "Updating xresources ..."
cp config/Xresources ~/.Xresources
cp config/xinitrc ~/.xinitrc
cp config/ripgreprc ~/.ripgreprc
cd ~
xrdb -merge .Xresources
cd -

# update emacs config
echo "Updating emacs ..."
test -d ~/.emacs.d || mkdir .emacs.d
test -f ~/.emacs && mv .emacs .emacs.$(date +%s)
cp -r apps/emacs/* ~/.emacs.d/

# update tmux
echo "Updating tmux ..."
cp apps/tmux/tmux.conf ~/.tmux.conf
