#!/bin/bash

function find_biggest() {
    set -e
    local level=$1
    local max_level=$2

    # Check if the maximum depth is reached
    if [ $level -gt $max_level ]; then
        return
    fi

    # Find the largest directory in the current path
    local biggest_dir=$(du -h -d 1 | sort -hr | sed -n 2p | awk '{print $2}')

    # Display the biggest directory and its size
    echo "$level $(pwd) => $biggest_dir $(du -hs "$biggest_dir" | awk '{print $1}')"

    # Move into the biggest directory and repeat
    cd "$biggest_dir"
    find_biggest $((level + 1)) $max_level
}

dirSizer() {
    echo "Checking directory sizes..."
    find_biggest 1 $1
}
