#!/bin/bash

mkdir -p ~/Workspace/questions

ask() {
  here=$(pwd)
  today=$(date +"%Y-%m-%d")
  now=$(date +"%s")
  cd ~/Workspace/questions
  mkdir -p $today
  cd $today
  touch ${now}.md
  echo "" > ${now}.md
  nvim ${now}.md
  echo "Copying question to clipboard ..."
  # Check if current os is linux
  if [ "$OSTYPE" == "darwin"* ]; then
    cat ${now}.md | pbcopy
  else
    cat ${now}.md | xclip
  fi
  cd $here
}



