#!/bin/bash

# open emacs in gui mode
emacsClientHereGui() {
    # TODO: launch daemon if not already running
    local f=${1:-.}
    emacsclient-snapshot -c $1
}

# open emacs in text mode
emacsClientHereText() {
    # TODO: launch daemon if not already running
    local f=${1:-.}
    emacsclient-snapshot -c $1
}
